import React, { useEffect, useState } from 'react';
import { api } from '../api/client';
import type { Alert } from '../api/client';
import { ShieldAlert, RefreshCw } from 'lucide-react';

const severityColor = (sev: string) => {
  if (sev === 'CRITICAL') return 'var(--status-critical)';
  if (sev === 'HIGH') return 'var(--status-high)';
  if (sev === 'MEDIUM') return 'var(--status-medium)';
  return 'var(--text-muted)';
};

export const AlertsPage: React.FC = () => {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchData = async () => {
    setLoading(true);
    try { setAlerts(await api.getAlerts()); }
    catch (e) { console.error(e); }
    finally { setLoading(false); }
  };

  useEffect(() => { fetchData(); }, []);

  return (
    <div className="animate-fade-in">
      <div className="page-header">
        <div>
          <h1 className="page-title">Active Alerts</h1>
          <p className="page-subtitle">Security alerts generated by behavioral detectors</p>
        </div>
        <button className="btn btn-sm" onClick={fetchData}>
          <RefreshCw size={13} /> Refresh
        </button>
      </div>

      {loading ? (
        <div style={{ textAlign: 'center', padding: '5rem 0', color: 'var(--text-muted)' }}>
          <RefreshCw size={20} className="animate-spin" style={{ margin: '0 auto 0.75rem' }} />
          <div style={{ fontSize: '0.85rem' }}>Loading…</div>
        </div>
      ) : (
        <div className="table-wrap">
          <table className="data-table">
            <thead>
              <tr>
                <th>Alert ID</th>
                <th>Severity</th>
                <th>Technique</th>
                <th>Agent ID</th>
                <th>Risk Score</th>
                <th>Summary</th>
                <th>Detected At</th>
              </tr>
            </thead>
            <tbody>
              {alerts.length === 0 ? (
                <tr>
                  <td colSpan={7} style={{ textAlign: 'center', padding: '2rem' }}>
                    No alerts found.
                  </td>
                </tr>
              ) : alerts.map(alert => (
                <tr key={alert.id} className="animate-fade-in">
                  <td>
                    <span style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: '0.78rem' }}>
                      {alert.id}
                    </span>
                  </td>
                  <td>
                    <span style={{
                      padding: '0.2rem 0.5rem',
                      borderRadius: 4,
                      fontSize: '0.7rem',
                      fontWeight: 700,
                      color: severityColor(alert.severity),
                      border: `1px solid ${severityColor(alert.severity)}30`,
                      background: `${severityColor(alert.severity)}15`
                    }}>
                      {alert.severity}
                    </span>
                  </td>
                  <td style={{ fontWeight: 500 }}>{alert.technique}</td>
                  <td>
                    <span style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: '0.78rem' }}>
                      {alert.agent_id}
                    </span>
                  </td>
                  <td>{alert.risk_score.toFixed(2)}</td>
                  <td style={{ maxWidth: '300px', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                    {alert.summary}
                  </td>
                  <td style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                    {new Date(alert.created_at).toLocaleString()}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};
